# Generated by Django 5.0.2 on 2024-03-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="height",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="position",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="weight",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
