# Generated by Django 5.0.2 on 2024-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_player_city_player_height_player_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="conference",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="games_lost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="games_won",
            field=models.IntegerField(default=0),
        ),
    ]
